services:
  app:
    build: .
    entrypoint: /home/node/app/.docker/entrypoint.sh
    container_name: healthcare-back-app
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    build: .docker/postgres
    container_name: healthcare-back-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/datas
    environment:
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
      - POSTGRES_PASSWORD=healthcare-back-secret
      - POSTGRES_DB=healthcare-back
